### ISSUE TITLE
Proxy server on PS3 HAN

### ISSUE THREAD

**Issue by KXRIST** [DADi590/HAN-Toolbox#3]
Hi,

i face a problem in ps3 HAN going online with proxy server latest version for both android and windows. 
I receive a message when trying psn login "a software update is required to login". 
I am on 4.82 with offline han activator.

these are the lines i use in the text file
# EU
Dest=85;CompatibleSystemSoftwareVersion=4.9000-;
Dest=85;IncrementalUpdateVersion=00010aad-00010aad;ImageVersion=00010b14;SystemSoftwareVersion=4.9000;CDN=http://deu01.ps3.update.playstation.net/update/ps3/image/eu/2023_0228_05fe32f5dc8c78acbcd84d36ee7fdc5b/PS3PATCH.PUP;CDN_Timeout=30;
Dest=85;ImageVersion=00010b14;SystemSoftwareVersion=4.9000;CDN=http://deu01.ps3.update.playstation.net/update/ps3/image/eu/2023_0228_05fe32f5dc8c78acbcd84d36ee7fdc5b/PS3UPDAT.PUP;CDN_Timeout=30;

if i change 4.90 with 4.82 i receive a message saying that my credentials are wrong.

Can you please help ?

**Comment by Edw590** [comment]
Hi. I don't know the lines by heart, but the default file on the Android app works (tested it myself a week ago on my PS3 which is still on 4.82 too). But have you heard that you must now use 2 Factor Authentication methods to login on the PS3? You can't login with your password anymore. Only with a 2FA generated one - which is what I did and I logged in successfully.

**Comment by KXRIST** [comment]
yes you are right, i had to generate a separate password for ps3 to login. everything works now.

thanks for help!

**Comment by Edw590** [comment]
happy to help!
